version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080
    environment:
      - TELEGRAM_KEY=${TELEGRAM_KEY}
      - SPACY_HOST=${SPACY_HOST}
    depends_on:
      - spacy
  spacy:
    image:  
    ports:
      - 80
  